import { Html, Line } from "@react-three/drei";
import type { ThreeEvent } from "@react-three/fiber";
import { memo, useMemo } from "react";
import { CatmullRomCurve3, Quaternion, Vector3 } from "three";
import { DEVICE_DEFAULTS } from "../domain/devices";
import { deviceTargetPorts, openRouteEndpoints, portCanStart, type OpenRouteEndpoint } from "../domain/devices";
import { lightingControlRelationLines } from "../domain/lighting-control-layout";
import { teeSocketSegments } from "../domain/network-geometry";
import type { BendArc, ConduitOverlayDocument, HostAttachment, JunctionBox, LightingControlGroup, NetworkDevice, NetworkDeviceType, RouteFitting, RoutePoint, RouteSegment, RoutingSystem, SurfaceChase, Vec3 } from "../domain/overlay";
import type { PlannedRoute } from "../domain/routing";
import { junctionBoxPortCanStart } from "../domain/routing";
import { sampleChase } from "../three/chase-geometry";
import type { DevicePositionDescription } from "../domain/device-positioning";

export type ConduitTool = "select" | "draw" | "branch" | "point" | "delete";
export type BranchPreview = { segmentId: string; point: Vec3; attachment?: HostAttachment; system: RoutingSystem; kind: "junction-box" | "tee"; sizeMm: [number, number, number]; valid: boolean };
export type DevicePreview = { deviceType: NetworkDeviceType; point: RoutePoint; valid: boolean; segmentId?: string };
export type DeviceTargetState = { system: RoutingSystem; portId: string | null; mode: "alignment" | "connect" | null };
type Props = { overlay: ConduitOverlayDocument; selectedId: string | null; selectedDevicePosition?: DevicePositionDescription; constructionMode: "construction" | "finished" | "xray"; visibleSystems: Record<RoutingSystem, boolean>; appliedSurfaceChases?: SurfaceChase[]; fallbackChaseKeys?: ReadonlySet<string>; departingSegments?: RouteSegment[]; draft: Vec3[]; draftColor: string; previewPlan?: PlannedRoute | null; conflictPoints?: Vec3[]; branchPreview?: BranchPreview | null; previewHost?: HostAttachment; alignmentAssist?: boolean; deviceTarget?: DeviceTargetState | null; devicePreview?: DevicePreview | null; deviceType: NetworkDeviceType; tool: ConduitTool; hoverId: string | null; controlBinding?: "create" | "edit" | null; visibleControlGroups?: LightingControlGroup[]; onControlDevice?: (id: string) => void; onSelect: (id: string, additive?: boolean) => void; onHover: (id: string | null) => void; onDeviceTarget: (device: NetworkDevice, point: Vec3 | null) => void; onBranchPreview: (preview: BranchPreview | null) => void; onDevicePreview: (preview: DevicePreview | null) => void; onBranch: (segment: RouteSegment, point: Vec3) => void; onInsertDevice: (segment: RouteSegment, point: Vec3) => void; onInsertEndpointDevice: (endpoint: OpenRouteEndpoint) => void; onConnectLegacy: (segment: RouteSegment, point: Vec3) => void; onStartDeviceRoute: (device: NetworkDevice, portId?: string, targetPoint?: [number, number, number]) => void; onStartJunctionRoute: (boxId: string, portId: string) => void; onStartEndpoint: (endpoint: OpenRouteEndpoint) => void; onDelete: (id: string) => void };
const point = (value: Vec3) => new Vector3(...value), vec = (value: Vector3): Vec3 => [value.x, value.y, value.z];
const EMPTY_FALLBACK_KEYS: ReadonlySet<string> = new Set();
const projectionOnSegment = (segment: RouteSegment, world: Vector3) => { const start = point(segment.start.position), delta = point(segment.end.position).sub(start), lengthSquared = delta.lengthSq(), t = lengthSquared < 1e-10 ? 0 : Math.max(0, Math.min(1, world.clone().sub(start).dot(delta) / lengthSquared)); return { point: vec(start.addScaledVector(delta, t)), t }; };
function segmentTransform(segment: RouteSegment) { const start = point(segment.start.position), end = point(segment.end.position), direction = end.clone().sub(start); return { midpoint: start.clone().add(end).multiplyScalar(.5), length: direction.length(), rotation: new Quaternion().setFromUnitVectors(new Vector3(0, 1, 0), direction.normalize()) }; }
function PipeMesh({ segment, color, opacity = 1 }: { segment: RouteSegment; color: string; opacity?: number }) { const transform = useMemo(() => segmentTransform(segment), [segment]); if (transform.length < .001) return null; const radius = segment.diameterMm / 2000, network = segment.system === "network"; return <group position={transform.midpoint} quaternion={transform.rotation}>{network && <mesh><cylinderGeometry args={[radius + .002, radius + .002, transform.length, 12]} /><meshStandardMaterial color="#94a3b8" transparent={opacity < 1} opacity={opacity} /></mesh>}<mesh><cylinderGeometry args={[radius, radius, transform.length + .002, 12]} /><meshStandardMaterial color={color} transparent={opacity < 1} opacity={opacity} roughness={.42} /></mesh></group>; }
function SegmentMesh({ segment, color, selected, hovered, visible, tool, branchable, insertable, deviceType, boxSize, onSelect, onHover, onBranchPreview, onDevicePreview, onBranch, onInsertDevice, onConnectLegacy, onDelete }: { segment: RouteSegment; color: string; selected: boolean; hovered: boolean; visible: boolean; tool: ConduitTool; branchable: boolean; insertable: boolean; deviceType: NetworkDeviceType; boxSize: [number, number, number]; onSelect: () => void; onHover: (active: boolean) => void; onBranchPreview: (preview: BranchPreview | null) => void; onDevicePreview: (preview: DevicePreview | null) => void; onBranch: (point: Vec3) => void; onInsertDevice: (point: Vec3) => void; onConnectLegacy: (point: Vec3) => void; onDelete: () => void }) { const transform = useMemo(() => segmentTransform(segment), [segment]); if (transform.length < .001 || !visible) return null; const display = tool === "delete" && hovered ? "#ef4444" : hovered && (tool === "branch" && branchable || tool === "point" && insertable || tool === "draw" && segment.legacyUnrooted) ? "#facc15" : selected ? "#f59e0b" : color; return <group position={transform.midpoint} quaternion={transform.rotation} onPointerMove={(event) => { event.stopPropagation(); onHover(true); const projected = projectionOnSegment(segment, event.point); if (tool === "branch" && branchable) { const clearance = segment.system === "sprinkler" ? segment.diameterMm / 1000 : boxSize[0] / 2000; onBranchPreview({ segmentId: segment.id, point: projected.point, attachment: segment.start.attachment?.hostId === segment.end.attachment?.hostId ? segment.start.attachment : undefined, system: segment.system, kind: segment.system === "sprinkler" ? "tee" : "junction-box", sizeMm: boxSize, valid: projected.t * transform.length > clearance && (1 - projected.t) * transform.length > clearance }); } if (tool === "point" && insertable) { const attachment = segment.start.attachment?.hostId === segment.end.attachment?.hostId ? segment.start.attachment : segment.start.attachment ?? segment.end.attachment; onDevicePreview({ deviceType, segmentId: segment.id, point: { position: projected.point, attachment }, valid: projected.t > .03 && projected.t < .97 }); } }} onPointerOut={() => { onHover(false); onBranchPreview(null); onDevicePreview(null); }} onClick={(event: ThreeEvent<MouseEvent>) => { event.stopPropagation(); const projected = projectionOnSegment(segment, event.point).point; if (tool === "delete") onDelete(); else if (tool === "point" && insertable) onInsertDevice(projected); else if (tool === "draw" && segment.legacyUnrooted) onConnectLegacy(projected); else { onSelect(); if (tool === "branch" && branchable) onBranch(projected); } }}><PipeMesh segment={{ ...segment, start: { position: [0, -transform.length / 2, 0] }, end: { position: [0, transform.length / 2, 0] } }} color={display} /></group>; }
function arcCurve(arc: BendArc) { const center = point(arc.center), start = point(arc.start).sub(center), radius = start.length(), normal = point(arc.normal).normalize(), tangent = new Vector3().crossVectors(normal, start).normalize(); return new CatmullRomCurve3(Array.from({ length: 17 }, (_, index) => center.clone().addScaledVector(start, Math.cos(arc.sweepRadians * index / 16)).addScaledVector(tangent, radius * Math.sin(arc.sweepRadians * index / 16))), false, "centripetal"); }
function standardElbowCurve(fitting: RouteFitting) { const radius = Math.max(fitting.diameterMm / 1000 * 1.5, .055), center = point(fitting.position.position), first = point(fitting.ports[0]?.direction ?? [-1, 0, 0]).normalize(), second = point(fitting.ports[1]?.direction ?? [0, 0, 1]).normalize(); return new CatmullRomCurve3([center.clone().addScaledVector(first, radius), center.clone(), center.clone().addScaledVector(second, radius)], false, "centripetal"); }
function bridgeCurve(fitting: RouteFitting) { const bridge = fitting.bridge!; return new CatmullRomCurve3([bridge.entry, bridge.crestStart, bridge.crestEnd, bridge.exit].map(point), false, "centripetal"); }
function FittingGeometry({ fitting, color, opacity = 1 }: { fitting: RouteFitting; color: string; opacity?: number }) { const radius = fitting.diameterMm / 1800; if (fitting.arc) return <mesh><tubeGeometry args={[arcCurve(fitting.arc), 24, fitting.diameterMm / 2000, 10, false]} /><meshStandardMaterial color={color} transparent={opacity < 1} opacity={opacity} /></mesh>; if (fitting.fitting === "bridge-bend" && fitting.bridge) return <mesh><tubeGeometry args={[bridgeCurve(fitting), 20, fitting.diameterMm / 2000, 10, false]} /><meshStandardMaterial color={color} transparent={opacity < 1} opacity={opacity} /></mesh>; if (fitting.fitting === "tee") return <group>{teeSocketSegments(fitting).map((segment) => <PipeMesh key={segment.id} segment={segment} color={color} opacity={opacity} />)}</group>; if (fitting.fitting === "elbow") return <mesh><tubeGeometry args={[standardElbowCurve(fitting), 16, fitting.diameterMm / 2000, 10, false]} /><meshStandardMaterial color={color} transparent={opacity < 1} opacity={opacity} /></mesh>; const direction = fitting.ports[1]?.direction ?? [1, 0, 0], length = Math.max(.035, fitting.diameterMm / 500), rotation = new Quaternion().setFromUnitVectors(new Vector3(0, 1, 0), point(direction).normalize()); return <mesh position={fitting.position.position} quaternion={rotation}><cylinderGeometry args={[radius * 1.15, radius * 1.15, length, 12]} /><meshStandardMaterial color={color} transparent={opacity < 1} opacity={opacity} /></mesh>; }
function JunctionBoxMesh({ box, color, selected, preview = false, valid = true }: { box: JunctionBox; color: string; selected?: boolean; preview?: boolean; valid?: boolean }) { const rotation = new Quaternion().setFromUnitVectors(new Vector3(0, 0, 1), point(box.frame?.front ?? box.position.attachment?.normal ?? [0, 1, 0]).normalize()), [w, h, d] = box.sizeMm.map((value) => value / 1000); return <mesh position={box.position.position} quaternion={rotation}><boxGeometry args={[w, h, d]} /><meshStandardMaterial color={!valid ? "#ef4444" : selected ? "#f59e0b" : color} transparent={preview} opacity={preview ? .62 : 1} /></mesh>; }
function DeviceGeometry({ device, color, preview = false, valid = true }: { device: NetworkDevice; color: string; preview?: boolean; valid?: boolean }) {
  const [w, h, d] = device.sizeMm.map((value) => value / 1000), material = <meshStandardMaterial color={valid ? color : "#ef4444"} transparent={preview} opacity={preview ? .62 : 1} roughness={.45} />, faceRotation = new Quaternion().setFromUnitVectors(new Vector3(0, 0, 1), point(device.frame?.front ?? device.orientation).normalize()), ignorePreviewRay = preview ? () => null : undefined;
  // Ceiling and suspended luminaires are disks facing down. Their conduit
  // ports are computed separately in the horizontal disk plane.
  if (device.deviceType === "luminaire") return <mesh raycast={ignorePreviewRay} position={device.position.position}><cylinderGeometry args={[w / 2, w / 2, d, 20]} />{material}</mesh>;
  if (device.deviceType === "sprinkler-head") return <group position={device.position.position}><mesh raycast={ignorePreviewRay} position={[0, h * .25, 0]}><cylinderGeometry args={[w * .12, w * .12, h * .5, 12]} />{material}</mesh><mesh raycast={ignorePreviewRay} position={[0, h * .52, 0]}><cylinderGeometry args={[w / 2, w / 2, Math.max(.006, d * .12), 20]} />{material}</mesh></group>;
  if (device.deviceType === "fire-inlet") return <mesh raycast={ignorePreviewRay} position={device.position.position} quaternion={faceRotation}><cylinderGeometry args={[w / 2, w / 2, d, 16]} />{material}</mesh>;
  return <group position={device.position.position} quaternion={faceRotation}><mesh raycast={ignorePreviewRay}><boxGeometry args={[w, h, d]} />{material}</mesh>{["strong-panel", "weak-panel"].includes(device.deviceType) && <mesh raycast={ignorePreviewRay} position={[0, 0, d / 2 + .002]}><boxGeometry args={[w * .84, h * .84, .006]} /><meshStandardMaterial color="#e5e7eb" /></mesh>}</group>;
}
const ChaseMesh = memo(function ChaseMesh({ chase }: { chase: SurfaceChase }) { return <Line points={sampleChase(chase)} color="#50351f" lineWidth={Math.max(2, chase.widthMm / 8)} transparent opacity={.82} />; });
function DeviceDimensionGuides({ device, description }: { device: NetworkDevice; description: DevicePositionDescription }) {
  const origin = device.position.position, guides: { key: string; start: Vec3; end: Vec3; label: string }[] = [];
  if (description.vertical) { const start: Vec3 = [origin[0], origin[1] - device.sizeMm[1] / 2000, origin[2]]; guides.push({ key: "vertical", start, end: [start[0], start[1] - description.vertical.millimeters / 1000, start[2]], label: `${description.vertical.millimeters} mm` }); }
  if (description.horizontal) { const u = device.position.attachment?.basis?.u ?? [1, 0, 0], sign = description.horizontal.direction, start: Vec3 = [origin[0] + u[0] * device.sizeMm[0] / 2000 * sign, origin[1] + u[1] * device.sizeMm[0] / 2000 * sign, origin[2] + u[2] * device.sizeMm[0] / 2000 * sign]; guides.push({ key: "horizontal", start, end: [start[0] + u[0] * description.horizontal.millimeters / 1000 * sign, start[1] + u[1] * description.horizontal.millimeters / 1000 * sign, start[2] + u[2] * description.horizontal.millimeters / 1000 * sign], label: `${description.horizontal.millimeters} mm` }); }
  for (const reference of description.planar ?? []) { const radius = footprintRadius(device, reference.direction), start: Vec3 = [origin[0] - reference.direction[0] * radius, origin[1], origin[2] - reference.direction[2] * radius]; guides.push({ key: reference.wallId, start, end: [start[0] - reference.direction[0] * reference.millimeters / 1000, start[1], start[2] - reference.direction[2] * reference.millimeters / 1000], label: `${reference.millimeters} mm` }); }
  return <group name="device-position-dimensions">{guides.map((guide) => { const middle = guide.start.map((value, axis) => (value + guide.end[axis]) / 2) as Vec3; return <group key={guide.key}><Line points={[guide.start, guide.end]} color="#f97316" lineWidth={1.5} /><mesh position={guide.start}><sphereGeometry args={[.02, 8, 6]} /><meshBasicMaterial color="#f97316" /></mesh><mesh position={guide.end}><sphereGeometry args={[.02, 8, 6]} /><meshBasicMaterial color="#f97316" /></mesh><Html position={middle} center distanceFactor={9}><span className="conduit-dimension-label">{guide.label}</span></Html></group>; })}</group>;
}
const footprintRadius = (device: NetworkDevice, direction: Vec3) => Math.abs(direction[0]) * device.sizeMm[0] / 2000 + Math.abs(direction[2]) * device.sizeMm[2] / 2000;
export function ConduitScene(props: Props) { const { overlay, selectedId, selectedDevicePosition, constructionMode, visibleSystems, appliedSurfaceChases = [], fallbackChaseKeys = EMPTY_FALLBACK_KEYS, departingSegments = [], draft, draftColor, previewPlan, conflictPoints = [], branchPreview, previewHost, alignmentAssist = false, deviceTarget = null, devicePreview, deviceType, tool, hoverId, controlBinding = null, visibleControlGroups = [], onControlDevice, onSelect, onHover, onDeviceTarget, onBranchPreview, onDevicePreview, onBranch, onInsertDevice, onInsertEndpointDevice, onConnectLegacy, onStartDeviceRoute, onStartJunctionRoute, onStartEndpoint, onDelete } = props, activeRouteSystem = deviceTarget?.system ?? null, activeTargetPortId = deviceTarget?.portId ?? null, deviceTargetMode = deviceTarget?.mode ?? null, visible = (system: RoutingSystem) => visibleSystems[system] && (constructionMode !== "finished" || system === "sprinkler"), previewColor = previewPlan?.canCommit === false ? "#ef4444" : draftColor, routeSystemById = useMemo(() => new Map<string, RoutingSystem>([...overlay.segments.map((segment) => [segment.id, segment.system] as const), ...overlay.fittings.map((fitting) => [fitting.id, fitting.system] as const)]), [overlay.segments, overlay.fittings]), visibleChases = useMemo(() => constructionMode === "finished" ? [] : appliedSurfaceChases.filter((chase) => visibleSystems[routeSystemById.get(chase.routeElementId) ?? "receptacle"] && [...fallbackChaseKeys].some((key) => key === chase.hostId || key.startsWith(`${chase.hostId}:`))), [appliedSurfaceChases, constructionMode, fallbackChaseKeys, routeSystemById, visibleSystems]), endpoints = useMemo(() => openRouteEndpoints(overlay).filter((endpoint) => visible(endpoint.system)), [overlay, visibleSystems]), selectedDevice = overlay.devices.find((device) => device.id === selectedId), hoveredTargetDevice = activeRouteSystem ? overlay.devices.find((device) => device.id === hoverId) : undefined, targetPorts = hoveredTargetDevice && activeRouteSystem ? deviceTargetPorts(hoveredTargetDevice, activeRouteSystem) : [], selectedTargetPort = targetPorts.find((port) => port.id === activeTargetPortId), targetingDevice = targetPorts.length > 0, targetReticleRotation = selectedTargetPort ? new Quaternion().setFromUnitVectors(new Vector3(0, 0, 1), point(selectedTargetPort.position.attachment?.normal ?? hoveredTargetDevice?.frame?.front ?? hoveredTargetDevice?.orientation ?? [0, 0, 1]).normalize()) : undefined, snapLabel = branchPreview?.valid ? "分支捕捉" : hoverId?.startsWith("open-end:") ? "开放管端" : hoveredTargetDevice ? `设备端口 · ${deviceTargetMode === "connect" ? "连接后结束" : "辅助对齐"}` : null, controlGroupLines = visibleControlGroups.flatMap((group) => lightingControlRelationLines(group, overlay.devices)); return <group name="routing">
  {selectedDevice && (selectedDevicePosition ?? (selectedDevice as NetworkDevice & { displayPosition?: DevicePositionDescription }).displayPosition) && <DeviceDimensionGuides device={selectedDevice} description={(selectedDevicePosition ?? (selectedDevice as NetworkDevice & { displayPosition: DevicePositionDescription }).displayPosition)} />}
  {departingSegments.map((segment) => <PipeMesh key={`departing:${segment.id}`} segment={segment} color="#f59e0b" opacity={.35} />)}
  {overlay.segments.map((segment) => <SegmentMesh key={segment.id} segment={segment} color={overlay.settings.colors[segment.system]} selected={selectedId === segment.id} hovered={hoverId === segment.id} visible={visible(segment.system)} tool={tool} branchable={visible(segment.system) && segment.system !== "network" && !segment.legacyUnrooted} insertable={visible(segment.system) && !segment.legacyUnrooted && DEVICE_DEFAULTS[deviceType].systems.includes(segment.system) && DEVICE_DEFAULTS[deviceType].canInsertMidSegment} deviceType={deviceType} boxSize={overlay.settings.junctionBoxSizeMm} onSelect={() => onSelect(segment.id)} onHover={(active) => onHover(active ? segment.id : null)} onBranchPreview={onBranchPreview} onDevicePreview={onDevicePreview} onBranch={(position) => onBranch(segment, position)} onInsertDevice={(position) => onInsertDevice(segment, position)} onConnectLegacy={(position) => onConnectLegacy(segment, position)} onDelete={() => onDelete(segment.id)} />)}
  {overlay.fittings.map((fitting) => visible(fitting.system) && <group key={fitting.id} onClick={(event) => { event.stopPropagation(); tool === "delete" ? onDelete(fitting.id) : onSelect(fitting.id); }}><FittingGeometry fitting={fitting} color={selectedId === fitting.id ? "#f59e0b" : overlay.settings.colors[fitting.system]} /></group>)}
  {overlay.junctionBoxes.map((box) => visible(box.system) && <group key={box.id} onClick={(event) => { event.stopPropagation(); tool === "delete" ? onDelete(box.id) : onSelect(box.id); }}><JunctionBoxMesh box={box} color={overlay.settings.colors[box.system]} selected={selectedId === box.id} />{tool === "draw" && box.ports.filter((port) => junctionBoxPortCanStart(overlay, box, port)).map((port) => <mesh key={port.id} position={port.position.position} onClick={(event) => { event.stopPropagation(); onStartJunctionRoute(box.id, port.id); }}><sphereGeometry args={[.018, 10, 8]} /><meshBasicMaterial color="#22c55e" /></mesh>)}</group>)}
  {overlay.devices.map((device) => <group key={device.id} onPointerMove={(event) => { event.stopPropagation(); onDeviceTarget(device, [event.point.x, event.point.y, event.point.z]); }} onPointerOut={() => onDeviceTarget(device, null)} onClick={(event) => { event.stopPropagation(); if (controlBinding) onControlDevice?.(device.id); else if (tool === "delete") onDelete(device.id); else if (tool === "draw") onStartDeviceRoute(device, undefined, [event.point.x, event.point.y, event.point.z]); else onSelect(device.id, event.nativeEvent.ctrlKey || event.nativeEvent.metaKey); }}><DeviceGeometry device={device} color={controlBinding === "create" && device.deviceType === "switch" ? "#22c55e" : selectedId === device.id || Boolean((device as NetworkDevice & { displaySelected?: boolean }).displaySelected) ? "#f59e0b" : overlay.settings.colors[device.systems[0]]} />{controlBinding === "create" && device.deviceType === "switch" && <mesh name="lighting-control-switch-target" position={device.position.position} renderOrder={24}><sphereGeometry args={[Math.max(...device.sizeMm) / 1700, 12, 8]} /><meshBasicMaterial color="#22c55e" wireframe depthTest={false} /></mesh>}{tool === "draw" && draft.length === 0 && device.ports.filter((port) => portCanStart(overlay, device, port, port.system)).map((port) => <mesh name={`snap:device-port:${port.id}`} key={port.id} position={port.position.position} onClick={(event) => { event.stopPropagation(); onStartDeviceRoute(device, port.id, [event.point.x, event.point.y, event.point.z]); }}><sphereGeometry args={[.018, 10, 8]} /><meshBasicMaterial color="#22c55e" /></mesh>)}{tool === "draw" && draft.length > 0 && hoverId === device.id && activeRouteSystem && deviceTargetPorts(device, activeRouteSystem).map((port) => { const active = port.id === activeTargetPortId, rotation = new Quaternion().setFromUnitVectors(new Vector3(0, 0, 1), point(port.position.attachment?.normal ?? device.frame?.front ?? device.orientation).normalize()); return <mesh name={`target:device-port:${port.id}`} key={`target:${port.id}`} position={port.position.position} quaternion={rotation} renderOrder={20} onPointerMove={(event) => { event.stopPropagation(); onDeviceTarget(device, [event.point.x, event.point.y, event.point.z]); }} onClick={(event) => { event.stopPropagation(); onStartDeviceRoute(device, port.id, [event.point.x, event.point.y, event.point.z]); }}><ringGeometry args={active ? [.012, .024, 20] : [.008, .014, 16]} /><meshBasicMaterial color={active ? "#22c55e" : "#86efac"} side={2} depthTest={false} /></mesh>; })}</group>)}
  {controlGroupLines.map((line) => <Line name="lighting-control-relation" key={line.key} points={line.points} color="#14b8a6" lineWidth={1.5} dashed dashSize={.08} gapSize={.05} depthTest={false} />)}
  {(tool === "draw" || (tool === "point" && ["socket", "switch", "network-outlet"].includes(deviceType))) && endpoints.filter((endpoint) => tool === "draw" || DEVICE_DEFAULTS[deviceType].systems.includes(endpoint.system)).map((endpoint) => <mesh name={`snap:open-end:${endpoint.segmentId}:${endpoint.end}`} key={`${endpoint.segmentId}:${endpoint.end}`} position={endpoint.point.position} onPointerMove={(event) => { event.stopPropagation(); onHover(`open-end:${endpoint.segmentId}:${endpoint.end}`); }} onPointerOut={() => onHover(null)} onClick={(event) => { event.stopPropagation(); if (tool === "draw") onStartEndpoint(endpoint); else onInsertEndpointDevice(endpoint); }}><sphereGeometry args={[.022, 12, 10]} /><meshBasicMaterial color={overlay.settings.colors[endpoint.system]} /></mesh>)}
  {visibleChases.map((chase) => <ChaseMesh key={chase.id} chase={chase} />)}
  {previewPlan ? <group>{previewPlan.segments.map((segment) => <PipeMesh key={segment.id} segment={segment} color={previewColor} opacity={.68} />)}{previewPlan.fittings.filter((fitting) => fitting.fitting === "elbow").map((fitting) => <FittingGeometry key={fitting.id} fitting={fitting} color={previewColor} opacity={.68} />)}</group> : draft.length >= 2 && <Line points={draft} color={previewColor} lineWidth={3} dashed />}
  {snapLabel && draft.length > 0 && !targetingDevice && <group position={draft[draft.length - 1]} name="snap-assist"><mesh><ringGeometry args={[.045, .07, 16]} /><meshBasicMaterial color="#22c55e" side={2} /></mesh></group>}
  {draft.length >= 1 && targetingDevice && <group position={draft[draft.length - 1]} quaternion={targetReticleRotation} name="target-reticle"><mesh renderOrder={21}><ringGeometry args={[.014, .027, 20]} /><meshBasicMaterial color="#22c55e" side={2} depthTest={false} /></mesh><Line points={[[-.035, 0, 0], [.035, 0, 0]]} color="#22c55e" lineWidth={1} depthTest={false} /><Line points={[[0, -.035, 0], [0, .035, 0]]} color="#22c55e" lineWidth={1} depthTest={false} /></group>}{draft.length >= 1 && !targetingDevice && <mesh position={draft[draft.length - 1]}><sphereGeometry args={[.055, 12, 10]} /><meshBasicMaterial color={previewColor} /></mesh>}{previewHost && draft.length >= 1 && !targetingDevice && <mesh position={draft[draft.length - 1]}><ringGeometry args={[.07, .095, 16]} /><meshBasicMaterial color={previewColor} side={2} /></mesh>}{conflictPoints.map((position, index) => <mesh key={index} position={position}><sphereGeometry args={[.08, 12, 10]} /><meshBasicMaterial color="#ef4444" /></mesh>)}
  {branchPreview && (branchPreview.kind === "junction-box" ? <JunctionBoxMesh box={{ id: "preview", type: "junction-box", system: branchPreview.system as Exclude<RoutingSystem, "sprinkler">, position: { position: branchPreview.point, attachment: branchPreview.attachment }, sizeMm: branchPreview.sizeMm, segmentIds: [], ports: [] }} color={overlay.settings.colors[branchPreview.system]} preview valid={branchPreview.valid} /> : <mesh position={branchPreview.point}><sphereGeometry args={[.075, 12, 10]} /><meshStandardMaterial color={branchPreview.valid ? overlay.settings.colors[branchPreview.system] : "#ef4444"} transparent opacity={.7} /></mesh>)}
  {devicePreview && <DeviceGeometry device={{ id: "preview", type: "network-device", deviceType: devicePreview.deviceType, name: "", position: devicePreview.point, sizeMm: DEVICE_DEFAULTS[devicePreview.deviceType].sizeMm, orientation: devicePreview.deviceType === "sprinkler-head" ? [0, 1, 0] : devicePreview.point.attachment?.normal ?? [0, 1, 0], systems: DEVICE_DEFAULTS[devicePreview.deviceType].systems, ports: [], createdAt: "" }} color={overlay.settings.colors[DEVICE_DEFAULTS[devicePreview.deviceType].systems[0]]} preview valid={devicePreview.valid} />}
</group>; }
