import React from 'react';
import type { BendArc, ConduitOverlayDocument, NetworkDevice, Vec3 } from '../domain/overlay';
import { DEVICE_DEFAULTS } from '../domain/devices';
import { useOverlayStore } from '../domain/store';
import { planFittingDisplay } from '../domain/network-plan';
import { PLAN_COLORS, type PlanContext } from './model';
import { DeviceSymbol } from './DeviceSymbol';
import { chooseVariantMarkerOffset, type CollisionBox } from './collision-layout';
function planArcPoints(arc: BendArc): Vec3[] {
  const subtract = (a: Vec3, b: Vec3): Vec3 => [a[0] - b[0], a[1] - b[1], a[2] - b[2]], center = arc.center, start = subtract(arc.start, center), radius = Math.hypot(...start), normalLength = Math.max(1e-9, Math.hypot(...arc.normal)), normal = arc.normal.map((value) => value / normalLength) as Vec3;
  const tangent: Vec3 = [(normal[1] * start[2] - normal[2] * start[1]) / Math.max(1e-9, radius), (normal[2] * start[0] - normal[0] * start[2]) / Math.max(1e-9, radius), (normal[0] * start[1] - normal[1] * start[0]) / Math.max(1e-9, radius)];
  return Array.from({ length: 17 }, (_, index) => { const angle = arc.sweepRadians * index / 16; return [center[0] + start[0] * Math.cos(angle) + tangent[0] * radius * Math.sin(angle), center[1] + start[1] * Math.cos(angle) + tangent[1] * radius * Math.sin(angle), center[2] + start[2] * Math.cos(angle) + tangent[2] * radius * Math.sin(angle)]; });
}
const WALL_ORIENTED_TYPES=new Set(['socket','switch','network-outlet','strong-panel','weak-panel','fire-inlet']);
export function devicePlanRotation(device:NetworkDevice,canvasRotation:number){
  if(!WALL_ORIENTED_TYPES.has(device.deviceType))return -canvasRotation;
  const direction=device.position.attachment?.normal??device.frame?.front??device.orientation,[x,,z]=direction;
  return Number.isFinite(x)&&Number.isFinite(z)&&Math.hypot(x,z)>1e-6?Math.atan2(x,-z)*180/Math.PI:-canvasRotation;
}

const ConduitPlanPermanent = React.memo(function ConduitPlanPermanent({ overlay, levelId, selectedId, onSelect, context, scale, rotation, devicesVisible, annotationScale, deviceVariants, dimensionObstacles }: { overlay: ConduitOverlayDocument; levelId: string; selectedId: string | null; onSelect: (id: string | null) => void; context: PlanContext; scale: number; rotation: number; devicesVisible: boolean; annotationScale: number; deviceVariants: Readonly<Record<string, string>>; dimensionObstacles: CollisionBox[] }) {
  const color = (id: string, system: keyof typeof PLAN_COLORS) => id === selectedId ? '#f36b00' : PLAN_COLORS[system];
  const select = (id: string) => (event: React.MouseEvent) => { event.stopPropagation(); onSelect(id); };
  return <g className="conduit-plan-permanent" fill="none" strokeWidth={1.8 / scale} strokeLinecap="round" strokeLinejoin="round">
    {overlay.segments.filter(s => context.segmentVisible(s) && context.segmentLevels.get(s.id)?.includes(levelId)).map(s => <g key={s.id} onClick={select(s.id)}><line x1={s.start.position[0]} y1={s.start.position[2]} x2={s.end.position[0]} y2={s.end.position[2]} stroke="transparent" strokeWidth={10 / scale}/><line x1={s.start.position[0]} y1={s.start.position[2]} x2={s.end.position[0]} y2={s.end.position[2]} stroke={color(s.id,s.system)}/></g>)}
    {overlay.fittings.filter(f => context.systemVisibility[f.system] && !context.hidden.has(f.id) && !context.hostHidden(f.position.attachment) && context.linkedLevel(f.segmentIds,f.position.attachment) === levelId).map(f => {
      const d = planFittingDisplay(f), stroke = color(f.id,f.system);
      if(d.kind === 'arc' || d.kind === 'bridge') return <polyline key={f.id} points={(d.kind === 'arc' ? planArcPoints(f.arc!) : d.points).map(p=>`${p[0]},${p[2]}`).join(' ')} stroke={stroke} strokeDasharray={d.kind === 'bridge' ? `${4/scale} ${3/scale}` : undefined} onClick={select(f.id)}/>;
      if(d.kind === 'connectors') return <g key={f.id} stroke={stroke} onClick={select(f.id)}>{d.lines.map((l,i)=><line key={i} x1={l.start[0]} y1={l.start[2]} x2={l.end[0]} y2={l.end[2]}/>)}</g>;
      return null;
    })}
    {devicesVisible && overlay.devices.filter(d => context.deviceVisible(d) && context.deviceLevel(d) === levelId).map(d => { const symbolRotation=devicePlanRotation(d,rotation),variant=deviceVariants[d.id],localObstacles=dimensionObstacles.map(box=>({minX:(box.minX-d.position.position[0])/(.018*annotationScale),minY:(box.minY-d.position.position[2])/(.018*annotationScale),maxX:(box.maxX-d.position.position[0])/(.018*annotationScale),maxY:(box.maxY-d.position.position[2])/(.018*annotationScale)})),marker=chooseVariantMarkerOffset([14,-10],localObstacles,10); return <g key={d.id} data-device-symbol={d.deviceType} transform={`translate(${d.position.position[0]} ${d.position.position[2]}) rotate(${symbolRotation}) scale(${.018*annotationScale})`} stroke={color(d.id,d.systems.find(s=>context.systemVisibility[s]) ?? d.systems[0])} strokeWidth="1.5" fill="#fff" onClick={select(d.id)}><rect x="-11" y="-11" width="22" height="22" fill="transparent" stroke="none"/><DeviceSymbol type={d.deviceType}/>{variant&&<g transform={`rotate(${-symbolRotation-rotation} ${marker[0]} ${marker[1]})`}><rect x={marker[0]-6} y={marker[1]-6} width="12" height="12" rx="2" stroke="none" fill="#fff" fillOpacity=".92"/><text data-device-variant={variant} x={marker[0]} y={marker[1]} textAnchor="middle" dominantBaseline="middle" fontSize="10" fontWeight="700" stroke="none" fill="#343434">{variant}</text></g>}</g>;})}
    {devicesVisible && overlay.junctionBoxes.filter(b => context.systemVisibility[b.system] && !context.hidden.has(b.id) && !context.hostHidden(b.position.attachment) && context.linkedLevel(b.segmentIds,b.position.attachment) === levelId).map(b=><g key={b.id} transform={`translate(${b.position.position[0]} ${b.position.position[2]}) rotate(${-rotation}) scale(${.018*annotationScale})`} stroke={color(b.id,b.system)} fill="#fff" strokeWidth="1.5" onClick={select(b.id)}><DeviceSymbol type="junction-box"/></g>)}
    {overlay.penetrations.filter(p => overlay.segments.some(s=>s.id===p.segmentId && context.segmentVisible(s)) && !context.hidden.has(p.id) && context.hostLevel(p.entry.attachment) === levelId).map(p=><g key={p.id} transform={`translate(${p.entry.position[0]} ${p.entry.position[2]}) scale(${1/scale})`} stroke="#9a6c39" strokeWidth="1" onClick={select(p.id)}><circle r="5"/><path d="M-7 0H7M0-7V7"/></g>)}
  </g>;
});
export function ConduitPlanOverlay({ overlay, levelId, selectedId, onSelect, context, scale, rotation, devicesVisible = true, annotationScale = 1, deviceVariants = {}, dimensionObstacles = [] }: { overlay: ConduitOverlayDocument | null; levelId: string; selectedId: string | null; onSelect: (id: string | null) => void; context: PlanContext | null; scale: number; rotation: number; devicesVisible?: boolean; annotationScale?: number; deviceVariants?: Readonly<Record<string, string>>; dimensionObstacles?: CollisionBox[] }) {
  const sharedPreview = useOverlayStore((state) => state.preview);
  if (!overlay || !context) return null;
  const preview = sharedPreview?.sourceSha === overlay.source.sha256 && (sharedPreview.levelId === levelId) ? sharedPreview : null;
  return <g className="conduit-plan-overlay" aria-label="只读管线平面图">
    <ConduitPlanPermanent overlay={overlay} levelId={levelId} selectedId={selectedId} onSelect={onSelect} context={context} scale={scale} rotation={rotation} devicesVisible={devicesVisible} annotationScale={annotationScale} deviceVariants={deviceVariants} dimensionObstacles={dimensionObstacles} />
    {preview && context.systemVisibility[preview.system] && <g className="conduit-plan-preview" pointerEvents="none" opacity=".78">
      {(() => { const color = preview.plan?.canCommit === false ? "#ef4444" : PLAN_COLORS[preview.system], width = 2 / scale; if (preview.plan) return <>{preview.plan.segments.map((segment) => <line key={segment.id} x1={segment.start.position[0]} y1={segment.start.position[2]} x2={segment.end.position[0]} y2={segment.end.position[2]} stroke={color} strokeWidth={width} strokeLinecap="round" strokeDasharray=".12 .07" />)}{preview.plan.fittings.filter((fitting) => Boolean(fitting.arc)).map((fitting) => <polyline key={fitting.id} points={planArcPoints(fitting.arc!).map((point) => `${point[0]},${point[2]}`).join(" ")} fill="none" stroke={color} strokeWidth={width} strokeLinecap="round" strokeLinejoin="round" strokeDasharray=".12 .07" />)}{preview.plan.fittings.filter((fitting) => Boolean(fitting.bridge)).map((fitting) => <polyline key={fitting.id} points={[fitting.bridge!.entry, fitting.bridge!.crestStart, fitting.bridge!.crestEnd, fitting.bridge!.exit].map((point) => `${point[0]},${point[2]}`).join(" ")} fill="none" stroke={color} strokeWidth={width} strokeLinecap="round" strokeDasharray=".04 .03" />)}</>; if (preview.points.length >= 2) return <polyline points={preview.points.map((point) => `${point.position[0]},${point.position[2]}`).join(" ")} fill="none" stroke={color} strokeWidth={width} strokeLinecap="round" strokeLinejoin="round" strokeDasharray=".12 .07" />; return null; })()}
      {preview.points.length > 0 && <circle cx={preview.points[preview.points.length - 1].position[0]} cy={preview.points[preview.points.length - 1].position[2]} r={.09*annotationScale} fill={preview.plan?.canCommit === false ? "#ef4444" : PLAN_COLORS[preview.system]} />}
      {devicesVisible && preview.branchNode?.kind === "junction-box" && <g transform={`translate(${preview.branchNode.position[0]} ${preview.branchNode.position[2]}) rotate(${-rotation}) scale(${.018*annotationScale})`} stroke={PLAN_COLORS[preview.system]} fill="#fff" strokeWidth="1.5"><DeviceSymbol type="junction-box"/></g>}
      {devicesVisible && preview.deviceNode && <g transform={`translate(${preview.deviceNode.position.position[0]} ${preview.deviceNode.position.position[2]}) rotate(${-rotation}) scale(${.018*annotationScale})`} stroke={preview.deviceNode.valid ? PLAN_COLORS[DEVICE_DEFAULTS[preview.deviceNode.deviceType].systems[0]] : "#ef4444"} fill="#fff" strokeWidth="1.5"><DeviceSymbol type={preview.deviceNode.deviceType}/></g>}
    </g>}
  </g>;
}
