import React from 'react';
import { formatMeasurement, type MeasurementUnit } from '../geometry/manual-measurement';
import { uprightDimensionAngle } from '../geometry/exterior-dimensions';
import type { Point, PointPositionDimension } from './model';

type DimensionPosition = { label: number; lineOffset: number };
const dot = (left: Point, right: Point) => left[0] * right[0] + left[1] * right[1];

export function PointPositionDimensions({dimensions,unit,viewRotation,annotationScale,onSelect,labelPositions={},lineOffsets={},onPositionChange,onLabelPositionChange,toPlanPoint,lineSnapTolerance=.12}:{dimensions:PointPositionDimension[];unit:MeasurementUnit;viewRotation:number;annotationScale:number;onSelect:(id:string)=>void;labelPositions?:Readonly<Record<string,number>>;lineOffsets?:Readonly<Record<string,number>>;onPositionChange?:(id:string,labelPosition:number,lineOffset:number)=>void;onLabelPositionChange?:(id:string,position:number)=>void;toPlanPoint?:(clientX:number,clientY:number)=>Point|null;lineSnapTolerance?:number}){
  const baseOffset=.28*annotationScale,overshoot=.06*annotationScale,tick=.055*annotationScale;
  const [draftPositions,setDraftPositions]=React.useState<Record<string,DimensionPosition>>({});
  const dragRef=React.useRef<{id:string;pointerId:number;start:Point;position:DimensionPosition;mode:'label'|'line'|null}|null>(null);
  const automaticOffset=(dimension:PointPositionDimension)=>baseOffset+dimension.lane*.18*annotationScale;
  const resolvedPosition=(dimension:PointPositionDimension):DimensionPosition=>draftPositions[dimension.id]??{label:labelPositions[dimension.id]??.5,lineOffset:lineOffsets[dimension.id]??automaticOffset(dimension)};
  const snapLineOffset=(dimension:PointPositionDimension, offset:number)=>{
    const coordinate=dot(dimension.reference,dimension.normal)+offset;
    const candidates=dimensions.filter(other=>other.id!==dimension.id&&Math.abs(dot(dimension.direction,other.direction))>.99).map(other=>dot(other.reference,dimension.normal)+resolvedPosition(other).lineOffset).filter(value=>Math.abs(value-coordinate)<=lineSnapTolerance).sort((left,right)=>Math.abs(left-coordinate)-Math.abs(right-coordinate));
    return candidates.length?candidates[0]! - dot(dimension.reference,dimension.normal):offset;
  };
  return <g className="point-position-dimensions" aria-label="点位定位尺寸">{dimensions.map(d=>{
    const position=resolvedPosition(d),offset=position.lineOffset,start:[number,number]=[d.reference[0]+d.normal[0]*offset,d.reference[1]+d.normal[1]*offset],end:[number,number]=[d.center[0]+d.normal[0]*offset,d.center[1]+d.normal[1]*offset],labelPoint:[number,number]=[start[0]+(end[0]-start[0])*position.label,start[1]+(end[1]-start[1])*position.label],extension=(point:Point):Point=>[point[0]+d.normal[0]*(offset+overshoot),point[1]+d.normal[1]*(offset+overshoot)],tickVector:[number,number]=[(d.direction[0]+d.normal[0])*tick,(d.direction[1]+d.normal[1])*tick],angle=uprightDimensionAngle(d.direction,viewRotation),label=formatMeasurement(d.valueMeters,unit)+(unit==='millimeters'?' mm':'');
    const finish=(event:React.PointerEvent,save:boolean)=>{const drag=dragRef.current;if(!drag||drag.id!==d.id||drag.pointerId!==event.pointerId)return;if(event.currentTarget.hasPointerCapture(event.pointerId))event.currentTarget.releasePointerCapture(event.pointerId);dragRef.current=null;const next=drag.position;if(save){onPositionChange?.(d.id,next.label,next.lineOffset);onLabelPositionChange?.(d.id,next.label);}setDraftPositions(current=>{const {[d.id]:_,...rest}=current;return rest;});};
    return <g key={d.id} data-point-position-dimension={d.sourceId} onClick={event=>{event.stopPropagation();onSelect(d.sourceId);}} style={{cursor:'pointer'}}>
      <line x1={d.referenceWitness[0]} y1={d.referenceWitness[1]} x2={extension(d.reference)[0]} y2={extension(d.reference)[1]} stroke="#626262" strokeWidth="1" vectorEffect="non-scaling-stroke"/><line x1={d.centerWitness[0]} y1={d.centerWitness[1]} x2={extension(d.center)[0]} y2={extension(d.center)[1]} stroke="#626262" strokeWidth="1" vectorEffect="non-scaling-stroke"/><line data-point-position-dimension-line={d.id} x1={start[0]} y1={start[1]} x2={end[0]} y2={end[1]} stroke="#626262" strokeWidth="1" vectorEffect="non-scaling-stroke"/>
      {[start,end].map((point,index)=><line key={index} x1={point[0]-tickVector[0]} y1={point[1]-tickVector[1]} x2={point[0]+tickVector[0]} y2={point[1]+tickVector[1]} stroke="#626262" strokeWidth="1" vectorEffect="non-scaling-stroke"/>)}
      <text data-point-position-dimension-label={d.id} x={labelPoint[0]} y={labelPoint[1]} transform={`rotate(${angle} ${labelPoint[0]} ${labelPoint[1]})`} textAnchor="middle" dominantBaseline="middle" fontFamily="DM Mono, monospace" fontSize={.18*annotationScale} fill="#404040" stroke="#fdfdfc" strokeWidth=".04" paintOrder="stroke" onPointerDown={event=>{event.stopPropagation();event.currentTarget.setPointerCapture(event.pointerId);const start=toPlanPoint?.(event.clientX,event.clientY);if(start)dragRef.current={id:d.id,pointerId:event.pointerId,start,position,mode:null};}} onPointerMove={event=>{const drag=dragRef.current;if(!drag||drag.id!==d.id||drag.pointerId!==event.pointerId)return;const point=toPlanPoint?.(event.clientX,event.clientY);if(!point)return;const delta:Point=[point[0]-drag.start[0],point[1]-drag.start[1]],along=dot(delta,d.direction),across=dot(delta,d.normal),mode=drag.mode??(Math.abs(along)>=Math.abs(across)?'label':'line'),next=mode==='label'?{...drag.position,label:Math.max(.08,Math.min(.92,drag.position.label+along/Math.max(.000001,Math.hypot(end[0]-start[0],end[1]-start[1]))))}:{...drag.position,lineOffset:snapLineOffset(d,drag.position.lineOffset+across)};dragRef.current={...drag,mode,position:next};setDraftPositions(current=>({...current,[d.id]:next}));}} onPointerUp={event=>finish(event,true)} onPointerCancel={event=>finish(event,false)}><title>{`点位中心定位尺寸；${d.referenceKind==='opening-edge'?'洞口边':d.referenceKind==='wall-face'?'模型墙面':d.referenceKind==='device-center'?'同类点位中心':'墙端'}至设备中心；来源 ${d.relatedIds.join(', ')}`}</title>{label}</text>
    </g>;
  })}</g>;
}
