import React from 'react';
import { formatMeasurement, type MeasurementUnit } from '../geometry/manual-measurement';
import { uprightDimensionAngle } from '../geometry/exterior-dimensions';
import type { Point, PointPositionDimension } from './model';

export function PointPositionDimensions({dimensions,unit,viewRotation,annotationScale,onSelect,labelPositions={},onLabelPositionChange,toPlanPoint}:{dimensions:PointPositionDimension[];unit:MeasurementUnit;viewRotation:number;annotationScale:number;onSelect:(id:string)=>void;labelPositions?:Readonly<Record<string,number>>;onLabelPositionChange?:(id:string,position:number)=>void;toPlanPoint?:(clientX:number,clientY:number)=>Point|null}){
  const baseOffset=.28*annotationScale,overshoot=.06*annotationScale,tick=.055*annotationScale;
  const [draftPositions,setDraftPositions]=React.useState<Record<string,number>>({});
  const draftPositionRef=React.useRef<Record<string,number>>({});
  return <g className="point-position-dimensions" aria-label="点位定位尺寸">{dimensions.map(d=>{const offset=baseOffset+d.lane*.18*annotationScale,start:[number,number]=[d.reference[0]+d.normal[0]*offset,d.reference[1]+d.normal[1]*offset],end:[number,number]=[d.center[0]+d.normal[0]*offset,d.center[1]+d.normal[1]*offset],mid:[number,number]=[(start[0]+end[0])/2,(start[1]+end[1])/2],extension=(point:[number,number]):[number,number]=>[point[0]+d.normal[0]*(offset+overshoot),point[1]+d.normal[1]*(offset+overshoot)],tickVector:[number,number]=[(d.direction[0]+d.normal[0])*tick,(d.direction[1]+d.normal[1])*tick],angle=uprightDimensionAngle(d.direction,viewRotation),label=formatMeasurement(d.valueMeters,unit)+(unit==='millimeters'?' mm':'');const saved= draftPositions[d.id]??labelPositions[d.id],labelPoint:[number,number]=saved===undefined?mid:[start[0]+(end[0]-start[0])*saved,start[1]+(end[1]-start[1])*saved];return <g key={d.id} data-point-position-dimension={d.sourceId} onClick={event=>{event.stopPropagation();onSelect(d.sourceId);}} style={{cursor:'pointer'}}>
    <line x1={d.referenceWitness[0]} y1={d.referenceWitness[1]} x2={extension(d.reference)[0]} y2={extension(d.reference)[1]} stroke="#626262" strokeWidth="1" vectorEffect="non-scaling-stroke"/><line x1={d.centerWitness[0]} y1={d.centerWitness[1]} x2={extension(d.center)[0]} y2={extension(d.center)[1]} stroke="#626262" strokeWidth="1" vectorEffect="non-scaling-stroke"/><line x1={start[0]} y1={start[1]} x2={end[0]} y2={end[1]} stroke="#626262" strokeWidth="1" vectorEffect="non-scaling-stroke"/>
    {[start,end].map((point,index)=><line key={index} x1={point[0]-tickVector[0]} y1={point[1]-tickVector[1]} x2={point[0]+tickVector[0]} y2={point[1]+tickVector[1]} stroke="#626262" strokeWidth="1" vectorEffect="non-scaling-stroke"/>)}
    <text data-point-position-dimension-label={d.id} x={labelPoint[0]} y={labelPoint[1]} transform={`rotate(${angle} ${labelPoint[0]} ${labelPoint[1]})`} textAnchor="middle" dominantBaseline="middle" fontFamily="DM Mono, monospace" fontSize={.18*annotationScale} fill="#404040" stroke="#fdfdfc" strokeWidth=".04" paintOrder="stroke" onPointerDown={event=>{event.stopPropagation();event.currentTarget.setPointerCapture(event.pointerId);}} onPointerMove={event=>{if(!event.currentTarget.hasPointerCapture(event.pointerId))return;const point=toPlanPoint?.(event.clientX,event.clientY);if(!point)return;const dx=end[0]-start[0],dy=end[1]-start[1],lengthSquared=dx*dx+dy*dy;if(lengthSquared<1e-9)return;const position=Math.max(.08,Math.min(.92,((point[0]-start[0])*dx+(point[1]-start[1])*dy)/lengthSquared));draftPositionRef.current={...draftPositionRef.current,[d.id]:position};setDraftPositions(current=>({...current,[d.id]:position}));}} onPointerUp={event=>{if(!event.currentTarget.hasPointerCapture(event.pointerId))return;event.currentTarget.releasePointerCapture(event.pointerId);const position=draftPositionRef.current[d.id]??labelPositions[d.id]??.5;onLabelPositionChange?.(d.id,position);delete draftPositionRef.current[d.id];setDraftPositions(current=>{const {[d.id]:_,...rest}=current;return rest;});}} onPointerCancel={event=>{if(event.currentTarget.hasPointerCapture(event.pointerId))event.currentTarget.releasePointerCapture(event.pointerId);delete draftPositionRef.current[d.id];setDraftPositions(current=>{const {[d.id]:_,...rest}=current;return rest;});}}><title>{`点位中心定位尺寸；${d.referenceKind==='opening-edge'?'洞口边':d.referenceKind==='wall-face'?'模型墙面':d.referenceKind==='device-center'?'同类点位中心':'墙端'}至设备中心；来源 ${d.relatedIds.join(', ')}`}</title>{label}</text>
  </g>;})}</g>;
}
